
export const TYPES = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    SET_USER:'SET_USER',
    EMPTY_CART:'EMPTY_CART',
    CART_SAVE_SHIPPING:'CART_SAVE_SHIPPING',
    CART_SAVE_PAYMENT:'CART_SAVE_PAYMENT',
    SET_SHIPPING_DATA:'SET_SHIPPING_DATA',
    CLEAR_CART:'CLEAR_CART',
    UPDATE_ITEM_PRICE:'UPDATE_ITEM_PRICE',
    SET_PRODUCT:'SET_PRODUCT'


}
