
export const TYPES = {
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REMOVE_ALL_FROM_BASKET:'REMOVE_ALL_FROM_BASKET',
    REMOVE_ONE_FROM_BASKET:'REMOVE_ONE_FROM_BASKET',
    SET_USER:'SET_USER',
    EMPTY_BASKET:'EMPTY_BASKET',
    SET_SHIPPING_DATA:'SET_SHIPPING_DATA',
    CLEAR_CART:'CLEAR_CART',
    UPDATE_ITEM_PRICE:'UPDATE_ITEM_PRICE',
    SET_PRODUCT:'SET_PRODUCT'


}
