const TYPES = {
  USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAIL: 'USER_SIGNIN_FAIL',

  USER_SIGNOUT: 'USER_SIGNOUT',

  USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
  USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
  USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
  USER_DETAILS_RESET: 'USER_DETAILS_RESET',

  USER_LIST_REQUEST: 'USER_LIST_REQUEST',
  USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
  USER_LIST_FAIL: 'USER_LIST_FAIL',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',

  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_LOGOUT: 'USER_LOGOUT',

  USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
  USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',
  USER_UPDATE_RESET:'USER_UPDATE_RESET',

   USER_DELETE_REQUEST : 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS : 'USER_DELETE_SUCCESS',
  USER_DELETE_FAIL : 'USER_DELETE_FAIL',
  USER_DELETE_RESET : 'USER_DELETE_RESET',


};

export default TYPES;
